#!/bin/bash

# Define the target IP and port
TARGET_IP="127.0.0.1"
TARGET_PORT="12345"

# Secret knocking sequences for different packet types
SEQUENCES=("nqXCT2xfFsvYktHG3d8gPV" "VqhEGfaeFTdSmUW7M4QkNz" "VXjdmp4QcBtH75S2Yf8gPx")

# Packet types corresponding to each sequence
PACKET_TYPES=("SYN" "ACK" "RST")

# Intervals between packets in seconds
INTERVALS=(1 2 3)

# Iterate through the sequences and send packets with corresponding intervals
for ((i=0; i<${#SEQUENCES[@]}; i++)); do
    echo -n "${SEQUENCES[$i]}" | nc -N -w 1 $TARGET_IP $TARGET_PORT
    sleep ${INTERVALS[$i]}
done
