CC=gcc
CFLAGS=-march=native -O2 -Wall -Wextra -fPIC -pipe -static -s
LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
PROGRAM_NAME=test

all:
	shc -f $(PROGRAM_NAME).sh -o $(PROGRAM_NAME)
	$(CC) -S -masm=intel -c $(PROGRAM_NAME).x.c $(CFLAGS)
	$(AS) $(PROGRAM_NAME).x.s -o $(PROGRAM_NAME).o
	$(CC) $(PROGRAM_NAME).o -o $(PROGRAM_NAME).x $(CFLAGS)
	upx --best $(PROGRAM_NAME).x
clean:
	rm -v $(PROGRAM_NAME).o $(PROGRAM_NAME).s $(PROGRAM_NAME).x.sh
