CC=gcc
CFLAGS=-march=native -Wall -Wextra -fPIC -pipe -D_GNU_SOURCE
LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

all:
	$(CC) -S -masm=intel -c knocker.c $(CFLAGS) -static -O2 --std=c17 -s
	$(AS) knocker.s -o knocker.o
	$(CC) knocker.o -o knocker $(CFLAGS) -static -O2 --std=c17 -s
	upx --best ./knocker
clean:
	rm -v knocker.o knocker.s
